const SKILLS = [
  'javascript',
  'typescript',
  'react',
  'react native',
  'node.js',
  'node',
  'express',
  'mongodb',
  'sql',
  'postgresql',
  'mysql',
  'python',
  'java',
  'c++',
  'c#',
  'html',
  'css',
  'tailwind',
  'git',
  'github',
  'rest api',
  'graphql',
  'docker',
  'kubernetes',
  'aws',
  'azure',
  'linux',
  'redux',
  'next.js',
  'nextjs',
  'jest',
  'testing',
  'ci/cd',
  'jwt',
  'oauth',
  'authentication',
  'authorization',
  'mui',
  'bootstrap',
  'vite',
  'webpack',
  'firebase',
  'redis',
  'microservices',
  'agile',
  'scrum',
  'data structures',
  'algorithms',
  'system design',
  'machine learning',
  'deep learning'
];

const EXPERIENCE_TERMS = ['intern', 'internship', 'developer', 'engineer', 'software engineer', 'full stack', 'frontend', 'backend', 'project'];
const EDUCATION_TERMS = ['bachelor', 'master', 'bsc', 'msc', 'computer science', 'software engineering', 'information technology', 'university', 'college'];

export { SKILLS, EXPERIENCE_TERMS, EDUCATION_TERMS };
